services:
  Zoltanlaca\EhSymfony\Handler:
    arguments:
      - '@http_client'
      - '%env(EH_ERROR_HANDLER_URL)%'
      - '%env(EH_ERROR_HANDLER_API_AUTH)%'
  Zoltanlaca\EhSymfony\EventListener\ExceptionListener:
    tags: [ kernel.event_listener ]
    arguments:
      - '@Zoltanlaca\EhSymfony\Handler'
      - 'Zoltanlaca\EhSymfony\DependencyInjection\EgonErrorHandlerConfiguration'
